package parall;


/**
* parall/_ParallMoverStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from parall.idl
* 28 сент€бр€ 2022 г. 0:14:17 MSK
*/

public class _ParallMoverStub extends org.omg.CORBA.portable.ObjectImpl implements parall.ParallMover
{

  public void moveParall (double x, double y, double z)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("moveParall", true);
                $out.write_double (x);
                $out.write_double (y);
                $out.write_double (z);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                moveParall (x, y, z        );
            } finally {
                _releaseReply ($in);
            }
  } // moveParall

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:parall/ParallMover:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ParallMoverStub
