package parall;


/**
* parall/ParallMover.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from parall.idl
* 28 сент€бр€ 2022 г. 0:14:17 MSK
*/

public interface ParallMover extends ParallMoverOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ParallMover
