package parall;


/**
* parall/ParallMoverOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from parall.idl
* 28 сент€бр€ 2022 г. 0:14:17 MSK
*/

public interface ParallMoverOperations 
{
  void moveParall (double x, double y, double z);
} // interface ParallMoverOperations
