package parall;


/**
* parall/ParallMoverPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from parall.idl
* 28 сент€бр€ 2022 г. 0:14:17 MSK
*/

public abstract class ParallMoverPOA extends org.omg.PortableServer.Servant
 implements parall.ParallMoverOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("moveParall", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // parall/ParallMover/moveParall
       {
         double x = in.read_double ();
         double y = in.read_double ();
         double z = in.read_double ();
         this.moveParall (x, y, z);
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:parall/ParallMover:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public ParallMover _this() 
  {
    return ParallMoverHelper.narrow(
    super._this_object());
  }

  public ParallMover _this(org.omg.CORBA.ORB orb) 
  {
    return ParallMoverHelper.narrow(
    super._this_object(orb));
  }


} // class ParallMoverPOA
