package parall;


/**
* parall/ParallMoverHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from parall.idl
* 28 сент€бр€ 2022 г. 0:14:17 MSK
*/

abstract public class ParallMoverHelper
{
  private static String  _id = "IDL:parall/ParallMover:1.0";

  public static void insert (org.omg.CORBA.Any a, parall.ParallMover that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static parall.ParallMover extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (parall.ParallMoverHelper.id (), "ParallMover");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static parall.ParallMover read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ParallMoverStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, parall.ParallMover value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static parall.ParallMover narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof parall.ParallMover)
      return (parall.ParallMover)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      parall._ParallMoverStub stub = new parall._ParallMoverStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static parall.ParallMover unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof parall.ParallMover)
      return (parall.ParallMover)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      parall._ParallMoverStub stub = new parall._ParallMoverStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
