package parall;

/**
* parall/ParallMoverHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from parall.idl
* 28 сент€бр€ 2022 г. 0:14:17 MSK
*/

public final class ParallMoverHolder implements org.omg.CORBA.portable.Streamable
{
  public parall.ParallMover value = null;

  public ParallMoverHolder ()
  {
  }

  public ParallMoverHolder (parall.ParallMover initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = parall.ParallMoverHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    parall.ParallMoverHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return parall.ParallMoverHelper.type ();
  }

}
